spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ai-service

server:
  port: ${SERVER_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS}
    hostname: ${EUREKA_INSTANCE_HOSTNAME}

auth:
  jwt:
    issuer: ${AUTH_JWT_ISSUER}
    secret: ${AUTH_JWT_SECRET}
